/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegodeturnos;

/**
 *
 * @author USER1
 */
public class Minijuego extends javax.swing.JFrame {
    boolean turno = true;
    boolean jugador = true;
    boolean defense = true;

    /**
     * Creates new form NewJFrame
     */
    public Minijuego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lbl_jugador2 = new javax.swing.JLabel();
        btn_curar2 = new javax.swing.JButton();
        lbl_vida1 = new javax.swing.JLabel();
        btn_atacar1 = new javax.swing.JButton();
        btn_atacar2 = new javax.swing.JButton();
        btn_absorb = new javax.swing.JButton();
        pb_vida2 = new javax.swing.JProgressBar();
        btn_static = new javax.swing.JButton();
        pb_vida1 = new javax.swing.JProgressBar();
        btn_defense = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_shockwave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_ganador = new javax.swing.JLabel();
        lbl_turno = new javax.swing.JLabel();
        btn_curar1 = new javax.swing.JButton();
        lbl_jugador1 = new javax.swing.JLabel();
        lbl_vida2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_reset = new javax.swing.JMenu();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_jugador2.setText("Jugador 2");

        btn_curar2.setText("Cure");
        btn_curar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_curar2MousePressed(evt);
            }
        });
        btn_curar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_curar2ActionPerformed(evt);
            }
        });

        lbl_vida1.setText("100");

        btn_atacar1.setText("Attack");
        btn_atacar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_atacar1MousePressed(evt);
            }
        });
        btn_atacar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atacar1ActionPerformed(evt);
            }
        });

        btn_atacar2.setText("Attack");
        btn_atacar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_atacar2MousePressed(evt);
            }
        });
        btn_atacar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atacar2ActionPerformed(evt);
            }
        });

        btn_absorb.setText("Absorb");
        btn_absorb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_absorbMousePressed(evt);
            }
        });
        btn_absorb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_absorbActionPerformed(evt);
            }
        });

        pb_vida2.setValue(100);
        pb_vida2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btn_static.setText("Static");
        btn_static.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_staticMousePressed(evt);
            }
        });
        btn_static.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_staticActionPerformed(evt);
            }
        });

        pb_vida1.setValue(100);

        btn_defense.setText("Defense");
        btn_defense.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_defenseMousePressed(evt);
            }
        });
        btn_defense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_defenseActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER1\\Pictures\\mp4\\minijuego examen\\Electabuzz.gif")); // NOI18N
        jLabel1.setToolTipText("");

        btn_shockwave.setText("Shock Wave");
        btn_shockwave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_shockwaveMousePressed(evt);
            }
        });
        btn_shockwave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_shockwaveActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER1\\Pictures\\mp4\\minijuego examen\\Tangela.gif")); // NOI18N

        jLabel4.setText("Turno:");

        lbl_turno.setText("Jugador 1");

        btn_curar1.setText("Cure");
        btn_curar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_curar1MousePressed(evt);
            }
        });
        btn_curar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_curar1ActionPerformed(evt);
            }
        });

        lbl_jugador1.setText("Jugador 1");

        lbl_vida2.setText("100");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER1\\Pictures\\mp4\\minijuego examen\\Pokemon_Trainer_Red_Animated_by_longcat93.gif")); // NOI18N

        menu_reset.setBorder(new javax.swing.border.MatteBorder(null));
        menu_reset.setText("Reset");
        menu_reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_reset.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        menu_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_resetMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu_resetMousePressed(evt);
            }
        });
        jMenuBar1.add(menu_reset);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pb_vida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lbl_jugador1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_vida1)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_curar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_defense))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_atacar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_absorb))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pb_vida2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lbl_vida2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_jugador2)
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel1)))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_turno)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_ganador, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_atacar2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_static))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_curar2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_shockwave)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_jugador2)
                    .addComponent(lbl_vida2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pb_vida2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_shockwave)
                    .addComponent(btn_curar2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_atacar1)
                            .addComponent(btn_absorb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_curar1)
                            .addComponent(btn_defense))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_vida1)
                            .addComponent(lbl_jugador1))
                        .addComponent(pb_vida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_atacar2)
                            .addComponent(btn_static))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_ganador, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_turno, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(95, 95, 95))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_resetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_resetMousePressed
        int vida1 = pb_vida1.getValue();
        vida1=100;
        pb_vida1.setValue(vida1);
        
        int vida2 = pb_vida2.getValue();
        vida2=100;
        pb_vida2.setValue(vida2);
        
        lbl_ganador.setText(null);
            
        String vd = Integer.toString(100);
        lbl_vida1.setText(vd);
            
        String vd2 = Integer.toString(100);
        lbl_vida2.setText(vd2);
        
        btn_defense.setVisible(true);
        btn_static.setVisible(true);
        
        boolean turno = true;
        boolean jugador = true;
        boolean defense = true;

        // TODO add your handling code here:
    }//GEN-LAST:event_menu_resetMousePressed

    private void menu_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_resetMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_menu_resetMouseClicked

    private void btn_curar2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_curar2MousePressed
        if(!turno){
            lbl_turno.setText("Jugador 1");
            int vida2 = pb_vida2.getValue();
            vida2+=10;
            pb_vida2.setValue(vida2);
            turno = true;
            lbl_ganador.setText(null);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_curar2MousePressed

    private void btn_curar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_curar2ActionPerformed
        int str = pb_vida1.getValue();
        String vd = Integer.toString(str);
        lbl_vida1.setText(vd);

        int str2 = pb_vida2.getValue();
        String vd2 = Integer.toString(str2);
        lbl_vida2.setText(vd2);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_curar2ActionPerformed

    private void btn_atacar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_atacar1MousePressed
        // TODO add your handling code here:
        if(turno){
            lbl_turno.setText("Jugador 2");
            int vida2 = pb_vida2.getValue();
            vida2-=10;
            pb_vida2.setValue(vida2);

            if(vida2<=0)
            lbl_ganador.setText("Jugador 1 ha ganado");

            else
            lbl_ganador.setText(null);
            turno = false;
        }
    }//GEN-LAST:event_btn_atacar1MousePressed

    private void btn_atacar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atacar1ActionPerformed
        int str = pb_vida1.getValue();
        String vd = Integer.toString(str);
        lbl_vida1.setText(vd);

        int str2 = pb_vida2.getValue();
        String vd2 = Integer.toString(str2);
        lbl_vida2.setText(vd2);

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_atacar1ActionPerformed

    private void btn_atacar2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_atacar2MousePressed
        if(!turno){
            if(!defense){
                lbl_turno.setText("Jugador 1");
                int vida1 = pb_vida1.getValue();
                vida1+=5;
                pb_vida1.setValue(vida1);
            }

            lbl_turno.setText("Jugador 1");
            int vida1 = pb_vida1.getValue();
            vida1-=10;
            pb_vida1.setValue(vida1);

            if(vida1<=0)
            lbl_ganador.setText("Jugador 2 ha ganado");

            else
            lbl_ganador.setText(null);
            turno = true;
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_atacar2MousePressed

    private void btn_atacar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atacar2ActionPerformed
        int str = pb_vida1.getValue();
        String vd = Integer.toString(str);
        lbl_vida1.setText(vd);

        int str2 = pb_vida2.getValue();
        String vd2 = Integer.toString(str2);
        lbl_vida2.setText(vd2);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_atacar2ActionPerformed

    private void btn_absorbMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_absorbMousePressed
        if(turno){
            lbl_turno.setText("Jugador 2");
            int vida1 = pb_vida1.getValue();
            vida1+=10;
            pb_vida1.setValue(vida1);

            int vida2 = pb_vida2.getValue();
            vida2-=20;
            pb_vida2.setValue(vida2);

            if(vida2<=0)
            lbl_ganador.setText("Jugador 1 ha ganado");

            else
            lbl_ganador.setText(null);
            turno = false;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_absorbMousePressed

    private void btn_absorbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_absorbActionPerformed
        int str = pb_vida1.getValue();
        String vd = Integer.toString(str);
        lbl_vida1.setText(vd);

        int str2 = pb_vida2.getValue();
        String vd2 = Integer.toString(str2);
        lbl_vida2.setText(vd2);

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_absorbActionPerformed

    private void btn_staticMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_staticMousePressed
        if(!turno){
            lbl_turno.setText("Jugador 2");
            int vida1 = pb_vida1.getValue();
            vida1-=5;
            pb_vida1.setValue(vida1);

            if(vida1<=0)
            lbl_ganador.setText("Jugador 2 ha ganado");

            else
            lbl_ganador.setText(null);
            turno = false;
        }
        btn_static.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_staticMousePressed

    private void btn_staticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_staticActionPerformed
        int str = pb_vida1.getValue();
        String vd = Integer.toString(str);
        lbl_vida1.setText(vd);

        int str2 = pb_vida2.getValue();
        String vd2 = Integer.toString(str2);
        lbl_vida2.setText(vd2);

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_staticActionPerformed

    private void btn_defenseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_defenseMousePressed
        if(turno){
            lbl_turno.setText("Jugador 2");
            turno = false;
        }
        defense = false;
        btn_defense.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_defenseMousePressed

    private void btn_defenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_defenseActionPerformed
        int str = pb_vida1.getValue();
        String vd = Integer.toString(str);
        lbl_vida1.setText(vd);

        int str2 = pb_vida2.getValue();
        String vd2 = Integer.toString(str2);
        lbl_vida2.setText(vd2);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_defenseActionPerformed

    private void btn_shockwaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_shockwaveMousePressed
        if(!turno){
            if(!defense){
                lbl_turno.setText("Jugador 1");
                int vida1 = pb_vida1.getValue();
                vida1+=5;
                pb_vida1.setValue(vida1);
            }
            lbl_turno.setText("Jugador 1");
            int vida1 = pb_vida1.getValue();
            vida1-=30;
            pb_vida1.setValue(vida1);

            if(vida1<=0)
            lbl_ganador.setText("Jugador 2 ha ganado");

            else
            lbl_ganador.setText(null);
            turno = true;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_shockwaveMousePressed

    private void btn_shockwaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_shockwaveActionPerformed
        int str = pb_vida1.getValue();
        String vd = Integer.toString(str);
        lbl_vida1.setText(vd);

        int str2 = pb_vida2.getValue();
        String vd2 = Integer.toString(str2);
        lbl_vida2.setText(vd2);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_shockwaveActionPerformed

    private void btn_curar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_curar1MousePressed
        if(turno){
            lbl_turno.setText("Jugador 2");
            int vida1 = pb_vida1.getValue();
            vida1+=10;
            pb_vida1.setValue(vida1);
            lbl_ganador.setText(null);
            turno = false;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_curar1MousePressed

    private void btn_curar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_curar1ActionPerformed
        int str = pb_vida1.getValue();
        String vd = Integer.toString(str);
        lbl_vida1.setText(vd);

        int str2 = pb_vida2.getValue();
        String vd2 = Integer.toString(str2);
        lbl_vida2.setText(vd2);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_curar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Minijuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Minijuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Minijuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Minijuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Minijuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_absorb;
    private javax.swing.JButton btn_atacar1;
    private javax.swing.JButton btn_atacar2;
    private javax.swing.JButton btn_curar1;
    private javax.swing.JButton btn_curar2;
    private javax.swing.JButton btn_defense;
    private javax.swing.JButton btn_shockwave;
    private javax.swing.JButton btn_static;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbl_ganador;
    private javax.swing.JLabel lbl_jugador1;
    private javax.swing.JLabel lbl_jugador2;
    private javax.swing.JLabel lbl_turno;
    private javax.swing.JLabel lbl_vida1;
    private javax.swing.JLabel lbl_vida2;
    private javax.swing.JMenu menu_reset;
    private javax.swing.JProgressBar pb_vida1;
    private javax.swing.JProgressBar pb_vida2;
    // End of variables declaration//GEN-END:variables
}
